language: node_js
node_js:
  - '8'

branches:
  only:
    - master

cache:
  yarn: true
  directories:
    - website/node_modules

before_install:
  - git config --global user.name "${GH_NAME}"
  - git config --global user.email "${GH_EMAIL}"
  - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc

script:
  - cd website && yarn install && yarn run typedoc && GIT_USER="${GH_NAME}" yarn run publish-gh-pages