language: node_js
node_js:
  - '8'

branches:
  only:
    - master

cache:
  yarn: true
  directories:
    - website/node_modules
    - $HOME/.m2

before_install:
  - git config --global user.name "${GH_NAME}"
  - git config --global user.email "${GH_EMAIL}"
  - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc

script:
  - cd website && yarn install && yarn run typedoc && yarn run build && cd -
  - cd codegen && yarn install && yarn run quicktype-java && yarn run quicktype-python && yarn run quicktype-cs && cd -
  - cd codegen && yarn run build-java && yarn run build-node && cd -

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GH_TOKEN
    email: $GH_EMAIL
    name: $GH_NAME
    verbose: true
    keep-history: true
    local-dir: website/build/finos-fo
    target_branch: gh-pages
    on:
      branch: master