language: node_js
node_js:
  - '8'

branches:
  only:
    - master

cache:
  yarn: true
  directories:
    - website/node_modules
    - $HOME/.m2

before_install:
  - git config --global user.name "${GH_NAME}"
  - git config --global user.email "${GH_EMAIL}"
  - echo "machine github.com login ${GH_NAME} password ${GH_TOKEN}" > ~/.netrc

script:
  # Build the website
  - cd website && yarn install && yarn run typedoc && yarn run build && cd -

  # Generate and test NPM bundle
  - cd npm-codegen && yarn install && yarn run node-bundle && cd local-sample && npm install && npm test && cd ../npm-sample && npm install && npm test && cd ../..
  
  # Generate and bundle code bindings: Java, Python and C#
  # - cd mvn-codegen && yarn run quicktype-java && yarn run quicktype-python && yarn run quicktype-cs && yarn run java-bundle && cd -

deploy:
  - provider: pages
    skip-cleanup: true
    github-token: $GH_TOKEN
    email: $GH_EMAIL
    name: $GH_NAME
    verbose: true
    keep-history: true
    local-dir: website/build/finos-fo
    target_branch: gh-pages
    on:
      branch: master